POST localhost:8080/category/adm/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTk3MjE1MjEsImV4cCI6MTY1OTcyNTEyMSwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoxfQ.wbNZyeq7ZXPO3hm4UgjDIeMBogHOEdAMp_e0kM9GRB0

{
  "name": "jizzax",
  "adminId": "12"
}

###
GET localhost:8080/category/adm/list
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTk3MjE1MjEsImV4cCI6MTY1OTcyNTEyMSwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoxfQ.wbNZyeq7ZXPO3hm4UgjDIeMBogHOEdAMp_e0kM9GRB0
