POST localhost:8080/report/user/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTgwODEwMTAsImV4cCI6MTY1ODA4NDYxMCwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoyfQ.vFdOWzNxIuc9QO4lk2TU7PyWi-RLRbCoieY4Pd3xWJA

{
  "entityId": "4028818681f3823c0181f3852a1f0000",
  "type": "CHANNEL",
  "content": "yaxshi chanak emas ekan"
}

###

GET localhost:8080/report/adm/deleteById/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTgwODQ0NzYsImV4cCI6MTY1ODA4ODA3NiwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoxfQ.CQzerNqCyShoH5qz3CIAs-bWVOpbmThk700E7BfLj1w


###

GET localhost:8080/report/adm/list/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTgwODQ0NzYsImV4cCI6MTY1ODA4ODA3NiwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoxfQ.CQzerNqCyShoH5qz3CIAs-bWVOpbmThk700E7BfLj1w
