POST localhost:8080/video_like/like
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTgwNDE5MDksImV4cCI6MTY1ODA0NTUwOSwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoyfQ.fjtwZkrwsEWqOIxdtq-yd5y6KHDLBCWmCchbyD_0Eak

{
  "videoId": "8a8a845c820147ff0182014cc59a0000"
}

###
 POST localhost:8080/video_like/dislike
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTgwNDE5MDksImV4cCI6MTY1ODA0NTUwOSwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoyfQ.fjtwZkrwsEWqOIxdtq-yd5y6KHDLBCWmCchbyD_0Eak

{
  "videoId": "8a8a845c820147ff0182014cc59a0000"
}
###
GET localhost:8080/video_like/videoListByLiked
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTc5OTQ5MzksImV4cCI6MTY1Nzk5ODUzOSwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoyfQ.n9Ju0RPmoOZgFprH00arn8RHMbFWrUL8zkqcJlkUAHY


